### ISSUE TITLE
Flutter: TODO Checklist Prior to Production Release

### ISSUE THREAD

**Issue by DaveNOTDavid** [DaveNOTDavid/dnd_headlines#15]
**WIP**:
- [x] App name
- [x] Add more news sources
- [x] News API Attribution Image
- [x] Proper logging for environments
- [x] Firebase Remote config settings (i.e. debug/developer mode)
- [x] Semantic versioning
- [x] Android: Splash Screen
- [x] iOS: Splash Screen
- [x] Android: Crashlytics (refer to Flutter package docs [here](https://pub.dev/packages/firebase_crashlytics#-readme-tab-))
- [x] iOS: ^
- [x] Android: Webview URL protocol fix (i.e. cleartext permission)
- [x] iOS: Webview URL protocol fix - confirm
- [x] Android: Update selection icon to something else more reasonable (i.e. bookmark) with respective description changes and such
- [x] iOS: Update selection icon to something else more reasonable (i.e. bookmark) with respective description changes and such
- [x] Android: Consider lines between each list item
- [x] iOS: Consider lines between each list item
- [x] Android: [App Size Considerations](https://flutter.dev/docs/perf/app-size)
- [x] iOS: [App Size Considerations](https://flutter.dev/docs/perf/app-size)
- [x] Android: Caching seems ridiculously large, particularly from the webview
- [x] iOS: Caching seems ridiculously large, particularly from the webview
- [x] Android: App Bundle or whatever means necessary to shrink size (because as of now, 6MB and 6.3MB for 32 and 64-bit ARM devices, respectively)
- [x] iOS: ^ similar option?
- [x] Android: Consider upgrading dependency versions to see if it makes a difference in app size
- [x] iOS: Consider upgrading dependency versions to see if it makes a difference in app size
- [ ] [Android: Deployment](https://flutter.dev/docs/deployment/android)
- [ ] [iOS: Deployment](https://flutter.dev/docs/deployment/ios)

**HIGH PRIORITY**
- Tally up total amount of resources that require a subscription. If enough, check alternatives for caching subscription login?
- [x] Bloomberg (since articles are around 140 days old and seems like there's also a free viewing limit)
- [x] Buzzfeed (unknown URL protocol scheme)
- [x] Daily Mail (no data as of 4/26/2020)
- [x] Financial Times (no data as of 4/26/2020)
- [ ] Fortune (some exclusives for subs)
- [x] FourFourTwo (error loading URLs and about ~17 days old as of 4/26/2020)
- [x] National Geographic (subscription dependent)
- [x] National Review (articles are at least 146 days old as of 4/26/2020)
- [ ] New Scientist (some exclusives for subs)
- [ ] TechCrunch (some exclusives for subs)
- [x] WSJ (most exclusives for subs)
- [ ] WaPO (some exclusives for subs)
- [x] Wired (all exclusives for subs)
- [x] ... is there a way to filter out on the News API for only non-exclusive content?

**Consider moving to a separate ticket:**
- [ ] Android: [Obfuscation](https://flutter.dev/docs/deployment/obfuscate)
- [ ] iOS: [Obfuscation](https://flutter.dev/docs/deployment/obfuscate)
- [ ] Android: Analytics (may require Firebase plan)
- [ ] iOS: Analytics (may require Firebase plan)
- [ ] Android: Any hope for image caching from source URL property?
- [ ] iOS: Any hope for image caching from source URL property?
